// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imhmywlwyflotafumdqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltaG15d2x3eWZsb3RhZnVtZHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjI1MzcsImV4cCI6MjA3NDUzODUzN30.VCno6cYWyOazi-PWB5294Q2QQe7cruSvP5bBTfDlLDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});